version: '1.5'

services:

  db:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=aalonso
      - POSTGRES_PASSWORD=ITBA
    container_name: postgres-db
    hostname: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql:/sql

networks:
  default:
    name: nt-pizza