version: '1.5'

services:

  db:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aalonso
      - POSTGRES_PASSWORD=ITBA
    container_name: postgres-db
    hostname: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  default:
    name: nt-pizza