version: '1.5'

services:

  postgres-db:
    build: ./database/
    ports:
      - 5432:5432
    container_name: postgres-db-pizza
    networks:
      - nt-pizza

networks:
  nt-pizza:
    driver: bridge