version: '1.5'

services:

  postgres-db:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    container_name: postgres-db-pizza
    hostname: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql:/sql
    networks:
      - nt-pizza

networks:
  nt-pizza:
    driver: bridge